### PR TITLE
Swedish :)

### PR DESCRIPTION
**Pull request by realslude**

### CODE REVIEW

**Comment by MrCrayfish** [comment]
Thank you!

**Comment by MrCrayfish** [comment]
Hey @realslude, I'm currently in the process of relicensing Goblin Traders. I would like your permission to relicense your contributions to Goblin Traders under MIT. Thank you.

**Comment by realslude** [comment]
@MrCrayfish yeah sure do whatever you want, it's your mod after all.

**Comment by realslude** [comment]
@MrCrayfish yeah sure do whatever you want, it's your mod after all. Also do you mind if I can help translate your other mods too?

**Pull request merged**
